In [1]:
import numpy as np

In [2]:
numbers_v2 = [element for element in range(1,11) if element%2 != 0]
numbers_v3 = np.array([element for element in range(1,11) if element%2 != 0])
print(numbers_v3 == numbers_v2)

[1, 3, 5, 7, 9]


In [3]:
arr = np.array(numbers, dtype="float64")
arr2 = np.array(numbers, ndmin = 3)
#array.dtype
#array = array.astype(np.float64)
#array = array.astype(np.int8)
#array.ndim
#expand = np.expand_dims(numbers, axis=0)
#array = np.squeeze(array2)
#array.shape
#array.reshape(1,6)
#np.reshape(array, (1,6))
#np.reshape(array, (1,6), "C")
#np.reshape(array, (1,6), "F")
#np.reshape(array, (1,6), "A")

numpy.ndarray

In [19]:
np.arange(0,20,2)
np.zeros(3)
np.zeros((10,10))
np.ones((10,10))
np.linspace(0,10,10)
np.eye(4)
np.random.rand(4)
np.random.randint(1,15)
np.random.randint(1,15,(10,10))

array([[ 3,  6, 11,  3, 14,  4,  4,  4,  3, 13],
       [ 6,  9,  4,  1, 12, 11,  1,  2,  3,  5],
       [ 9,  3,  9, 12, 13,  9,  9,  1, 13,  6],
       [ 7, 12, 10, 13,  6, 13, 10, 10, 11,  6],
       [ 3,  8,  7, 11, 13,  5,  6, 10, 14,  6],
       [ 2, 13, 10,  4, 13,  9,  7,  2,  7,  8],
       [14,  2,  7, 10,  1, 12, 12,  2,  4,  9],
       [11,  2,  8,  2, 13, 10, 12, 10,  9,  9],
       [ 3, 11, 10,  9, 13,  4,  4,  7, 14, 14],
       [ 8,  1,  8, 13, 14,  6,  1,  8,  3, 12]])

In [6]:
import numpy as np
#array = np.random.randint(1,15,(2,2))
#array.max()
#array.max(1)
#array.max(0)
#array.argmax()
#array.min()
#array.argmin()
#array.ptp()
#array.percentile(50)
#np.percentil(array,50)
#np.sort()
#np.median(array,1)
#np.std(array)
#np.var(array)
#np.mean(array)
a = np.array([[1,2],[3,4]])
b = np.array([4,6])
b = np.expand_dims(b,axis=0)
np.concatenate((a,b.T), axis=1)

array([[1, 2, 4],
       [3, 4, 6]])

In [9]:
import numpy as np
array = np.arange(0,11)
trozo = array.copy()
trozo = trozo[0:6]
trozo[:] = 0
print(trozo)
print(array)


[0 0 0 0 0 0]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [19]:
import numpy as np
f = np.linspace(1,10,10, dtype="int8")
indice = f > 5
f[indice & (f<9)]
f[f > 5] = 99
f

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [27]:
import numpy as np
lista = [1,2]
lista2 = np.arange(0,10)
lista3 = lista2.copy()
lista3 * 2
matriz = lista2.reshape(2,5)
matriz2 = matriz.copy()
matriz4 = np.matmul(matriz,matriz2.T)
matriz5 = matriz @ matriz2.T

In [33]:
y = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]]).ndim
print(y)


3


In [9]:
import pandas as pd

psg = pd.Series(["navas","mbappe","messi"], index = [1,2,3]) 
pdg2 = pd.Series({1:"navas",2:"mbappe",3:"messi"})
print(psg == pdg2)
dict={"gamer":["navas","mbappe","messi"], "altura": [1,2,3],"jugo":["naranja", "sopa", "manzana"]}
data = pd.DataFrame(dict, index=[1,2,3])
data.columns



1    True
2    True
3    True
dtype: bool


Index(['gamer', 'altura', 'jugo'], dtype='object')